version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8080 financial_system.wsgi:application

    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: always

volumes:
  postgres_data: