# Generated by Django 5.1.2 on 2024-10-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stockprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('initial_investment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('final_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('roi', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_drawdown', models.DecimalField(decimal_places=2, max_digits=5)),
                ('trades_executed', models.IntegerField()),
            ],
        ),
    ]
