name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    # Authenticate with Google Cloud
    - name: Authenticate to Google Cloud
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" > $HOME/GCP_SA_KEY.json
        gcloud auth activate-service-account --key-file=$HOME/GCP_SA_KEY.json
        gcloud config set project financial-439004

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Build Docker image
    - name: Build the Docker image
      run: |
        docker build -t gcr.io/financial-439004/financial_system:latest .

    # Push Docker image to Google Container Registry
    - name: Push Docker image to Google Container Registry
      run: |
        docker push gcr.io/financial-439004/financial_system:latest

    # Submit the build to Google Cloud
    - name: Submit build to Google Cloud
      run: |
        gcloud builds submit --config=cloudbuild.yaml

    # Deploy to Google Cloud Run
    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy financial-system \
        --image gcr.io/financial-439004/financial_system:latest \
        --platform managed \
        --region us-central1 \
        --allow-unauthenticated \
        --add-cloudsql-instances=financial-439004:us-central1:financial-db-instance \
        --env-vars-file=env.yaml
