name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Google Cloud
      run: echo "${{ secrets.GCP_SA_KEY }}" | docker login -u _json_key --password-stdin https://gcr.io

    - name: Build and push Docker image
      run: |
        docker-compose build
        docker tag financial_system:latest gcr.io/financial-439004/financial_system:latest
        docker push gcr.io/financial-439004/financial_system:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy financial-system \
        --image gcr.io/financial-439004/financial_system:latest \
        --platform managed \
        --region us-central1 \
        --allow-unauthenticated \
        --add-cloudsql-instances=financial-439004:us-central1:financial-db-instance \
        --env-vars-file=env.yaml
